module.exports = {
  EXPIRADO: -5,
  DESAPROBADO_EN_LEGALES:-2,
  DESAPROBADO_EN_MESA:-1,
  NUEVO_SIN_VALIDAR:0,
  APROBADO_EN_MESA:1,
  NUEVO_EN_LEGALES:2,
  APROBADO_EN_LEGALES:3,
  ESTAMPILLADO:4,
  CORREGIDO_PARA_MESA:5,
  CORREGIDO_PARA_LEGALES:6
}